/**
 * Every Arabic string in the interface (spec §12.1). Nothing is written inline
 * in a component — one file to review, one file to hand a translator, and no
 * hunting through templates when the municipality changes a term.
 */
export const T = {
  app: {
    name: 'أمان',
    tagline: 'سلامة الغذاء في نابلس',
    authority: 'بلدية نابلس',
    department: 'صحة الأغذية',
    attribution: 'الدرجة صادرة عن بلدية نابلس — أمان أداة بيد البلدية ولا يصدر أي تقييم.',
  },

  home: {
    lede: 'امسح رمز الاستجابة السريعة على باب المنشأة لتطّلع على درجتها الصحية.',
    demoLabel: 'منشأة للعرض',
    inspectorEntry: 'دخول المفتشين',
  },

  common: {
    loading: 'جارٍ التحميل…',
    retry: 'أعد المحاولة',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    cancel: 'إلغاء',
    save: 'حفظ',
    of: 'من',
    day: 'يوم',
    days: 'يوماً',
    none: 'لا يوجد',
  },

  grade: {
    label: 'الدرجة',
    notInspected: 'لم يُفتَّش بعد',
    meaning: {
      A: 'مطابق للمعايير',
      B: 'مخالفات بسيطة',
      C: 'مخالفات مؤثرة تستوجب المتابعة',
      D: 'مخالفات جسيمة تستوجب إجراءً عاجلاً',
    } as Record<string, string>,
  },

  publicPage: {
    recordTitle: 'بيانات السجل',
    lastInspection: 'آخر تفتيش',
    score: 'النتيجة',
    openViolations: 'مخالفات مفتوحة',
    neverInspected: 'لم يسبق تفتيش هذه المنشأة',
    violationsTitle: 'مخالفات قيد المتابعة',
    ownerResponded: 'ردّ صاحب المنشأة وينتظر التحقق',
    historyTitle: 'سجل التفتيش',
    historyEmpty: 'لا يوجد سجل تفتيش سابق.',
    violationsEmpty: 'لا توجد مخالفات مفتوحة.',
    complaintCta: 'قدّم شكوى عن هذه المنشأة',
    suspended: 'هذه المنشأة موقوفة أو مغلقة بقرار من البلدية.',
    notFound: 'هذا الرمز غير مسجّل لدى البلدية.',
    notFoundHint: 'تأكد من مسح الملصق الرسمي الموجود على باب المنشأة.',
  },

  complaint: {
    title: 'تقديم شكوى',
    reporting: 'الشكوى بخصوص',
    categoryLabel: 'ما الذي لاحظته؟',
    category: {
      HYGIENE: 'النظافة العامة',
      EXPIRED: 'مواد منتهية الصلاحية أو فاسدة',
      REFRIGERATION: 'التبريد أو التخزين',
      STAFF: 'نظافة العاملين',
      PESTS: 'حشرات أو قوارض',
      OTHER: 'أخرى',
    } as Record<string, string>,
    descriptionLabel: 'صف ما لاحظته باختصار',
    descriptionPlaceholder: 'مثال: صراصير قرب منطقة التحضير',
    remaining: 'حرفاً متبقياً',
    photoLabel: 'أضف صورة (اختياري)',
    photoHint: 'الشكاوى المرفقة بصورة تُعطى أولوية أعلى.',
    photoAdd: 'التقط صورة',
    photoRemove: 'حذف الصورة',
    phoneLabel: 'رقم هاتفك (اختياري — للتحديثات فقط)',
    phoneHint: 'لا يظهر لصاحب المنشأة أبداً.',
    submit: 'إرسال الشكوى',
    submitting: 'جارٍ الإرسال…',
    failed: 'تعذّر إرسال الشكوى. حاول مرة أخرى.',
    successTitle: 'تم استلام الشكوى',
    referenceLabel: 'الرقم المرجعي',
    copy: 'نسخ',
    copied: 'تم النسخ',
    saveNumber: 'احتفظ بهذا الرقم لمتابعة حالة الشكوى.',
    trackNow: 'تابع الشكوى',
    backToEstablishment: 'العودة إلى صفحة المنشأة',
    // This line is what stops a citizen expecting an instant downgrade.
    gradeNote: 'الشكوى تُقدّم المنشأة في دور التفتيش، ولا تغيّر الدرجة. الدرجة لا تتغيّر إلا بتفتيش.',
  },

  track: {
    title: 'متابعة شكوى',
    lede: 'أدخل الرقم المرجعي الذي استلمته عند تقديم الشكوى.',
    referenceLabel: 'الرقم المرجعي',
    submit: 'عرض الحالة',
    notFound: 'لا توجد شكوى بهذا الرقم المرجعي.',
    submittedAt: 'تاريخ التقديم',
    step: {
      SUBMITTED: 'تم الاستلام',
      UNDER_REVIEW: 'قيد المراجعة',
      ASSIGNED: 'تم تحديد زيارة تفتيش',
      INSPECTED: 'تم التفتيش',
      CLOSED: 'مغلقة',
      DUPLICATE: 'مكرّرة — دُمجت مع شكوى سابقة',
      REJECTED: 'مرفوضة',
    } as Record<string, string>,
    pending: 'قيد الانتظار',
  },

  auth: {
    title: 'دخول المفتشين',
    subtitle: 'بلدية نابلس — دائرة صحة الأغذية',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    submit: 'تسجيل الدخول',
    signingIn: 'جارٍ الدخول…',
    failed: 'تعذّر تسجيل الدخول. تحقق من البيانات وحاول مجدداً.',
    signOut: 'تسجيل الخروج',
  },

  queue: {
    title: 'جولة اليوم',
    subtitle: 'مرتّبة حسب الأولوية',
    assigned: 'مسندة اليوم',
    start: 'ابدأ التفتيش',
    resume: 'أكمل التفتيش',
    empty: 'لا توجد منشآت مسندة اليوم.',
    emptyHint: 'اسحب للأسفل لتحديث القائمة.',
    refresh: 'تحديث القائمة',
    lastUpdated: 'آخر تحديث',
    offlineList: 'تعرض القائمة المحفوظة — قد يكون الترتيب قد تغيّر.',
    riskLabel: 'الأولوية',
    riskHigh: 'مرتفعة',
    riskMid: 'متوسطة',
    riskLow: 'منخفضة',
    why: 'سبب الترتيب',
    loadFailed: 'تعذّر تحميل القائمة.',
  },

  checklist: {
    section: 'القسم',
    progress: 'مكتمل',
    runningScore: 'النتيجة الحالية',
    result: { PASS: 'مطابق', FAIL: 'مخالف', NA: 'لا ينطبق' } as Record<string, string>,
    severity: { CRITICAL: 'حرجة', MAJOR: 'كبيرة', MINOR: 'بسيطة' } as Record<string, string>,
    measured: 'القراءة المسجّلة',
    note: 'ملاحظة',
    notePlaceholder: 'موقع القراءة أو تفصيل المخالفة',
    addPhoto: 'أرفق صورة',
    photoRequired: 'المخالفة الحرجة تتطلب صورة قبل المتابعة.',
    photoAttached: 'صورة مرفقة',
    removePhoto: 'حذف الصورة',
    unanswered: 'لم يُجب بعد',
    autosaved: 'محفوظ على الجهاز',
    toReview: 'المراجعة والإرسال',
    incomplete: 'أجب على جميع بنود هذا القسم للمتابعة.',
    loadFailed: 'تعذّر تحميل بيانات المنشأة. اتصل بالشبكة وحاول مجدداً.',
    abandon: 'إنهاء التفتيش وحذف المسودّة',
    abandonConfirm: 'سيتم حذف هذه المسودّة نهائياً. هل تريد المتابعة؟',
  },

  review: {
    title: 'المراجعة والإرسال',
    failedTitle: 'المخالفات المسجّلة',
    noFailures: 'لم تُسجَّل أي مخالفة في هذه الزيارة.',
    outcome: 'نتيجة الزيارة',
    gradeChange: 'تغيّر الدرجة',
    recommendation: 'الإجراء الموصى به',
    recommendationHint: 'يمكنك تعديل النص قبل الإرسال.',
    deadline: 'المهلة',
    signature: 'توقيع المفتش',
    signatureHint: 'وقّع داخل الإطار.',
    clearSignature: 'مسح التوقيع',
    signatureRequired: 'التوقيع مطلوب قبل الإرسال.',
    submit: 'إرسال التفتيش',
    submitting: 'جارٍ الإرسال…',
    confirmTitle: 'الإرسال نهائي',
    confirmBody:
      'لا يمكن تعديل التفتيش بعد إرساله. أي تصحيح يستلزم تفتيشاً جديداً مع بيان السبب.',
    confirmAccept: 'أرسل نهائياً',
    queued: 'لا يوجد اتصال — أُدرج التفتيش في قائمة الإرسال وسيُرسل تلقائياً.',
    submitted: 'تم إرسال التفتيش وتحديث الدرجة.',
    viewPublic: 'اعرض الصفحة العامة',
    backToQueue: 'العودة إلى الجولة',
  },

  admin: {
    title: 'إدارة البلدية',
    navComplaints: 'الشكاوى',
    navPlanning: 'خطة التفتيش',
    loadFailed: 'تعذّر تحميل البيانات.',

    complaints: {
      title: 'فرز الشكاوى',
      empty: 'لا توجد شكاوى مطابقة.',
      age: 'العمر',
      assigned: 'المفتش',
      contact: 'هاتف مقدّم الشكوى',
      contactNone: 'لم يُترك رقم',
      contactWarning: 'بيانات مقدّم الشكوى لا تظهر لصاحب المنشأة ولا للمفتش.',
      hasPhoto: 'بصورة',
      noPhoto: 'بلا صورة',
      duplicateGroup: 'ضمن مجموعة مكرّرة',
      duplicateNote: 'شكاوى عن المنشأة نفسها والنوع نفسه خلال ٧٢ ساعة — تُحتسب مرة واحدة في الأولوية.',
      filterAll: 'الكل',
      filterStatus: 'الحالة',
      filterEvidence: 'الأدلة',
      actionAssign: 'إسناد',
      actionReject: 'رفض',
      actionClose: 'إغلاق',
      chooseInspector: 'اختر مفتشاً',
      chooseReason: 'اختر سبب الرفض',
      confirmReject: 'سيُسجَّل الرفض في سجل التدقيق باسمك ولا يمكن التراجع عنه. هل تريد المتابعة؟',
      reason: {
        OUT_OF_JURISDICTION: 'خارج اختصاص البلدية',
        INSUFFICIENT_DETAIL: 'التفاصيل غير كافية',
        NOT_FOOD_SAFETY: 'لا تتعلق بسلامة الغذاء',
        ESTABLISHMENT_CLOSED: 'المنشأة مغلقة',
        ABUSIVE_OR_SPAM: 'مسيئة أو عشوائية',
      } as Record<string, string>,
      status: {
        SUBMITTED: 'مستلمة',
        UNDER_REVIEW: 'قيد المراجعة',
        ASSIGNED: 'مُسندة',
        INSPECTED: 'تم التفتيش',
        CLOSED: 'مغلقة',
        DUPLICATE: 'مكرّرة',
        REJECTED: 'مرفوضة',
      } as Record<string, string>,
    },

    planning: {
      title: 'خطة التفتيش حسب الأولوية',
      lede: 'الترتيب محسوب من صيغة معلنة، وكل عامل ظاهر مع وزنه ومساهمته.',
      lastInspection: 'آخر تفتيش',
      never: 'لم يُفتَّش',
      breakdown: 'تفصيل العوامل',
      hide: 'إخفاء التفصيل',
      factor: 'العامل',
      weight: 'الوزن',
      contribution: 'المساهمة',
      refresh: 'تحديث',
      empty: 'لا توجد منشآت نشطة.',
      gradeNote: 'الأولوية ترتّب الزيارات فقط. الدرجة لا تتغيّر إلا بتفتيش.',
    },
  },

  owner: {
    title: 'بوابة صاحب المنشأة',
    lastInspection: 'آخر تفتيش',
    nextInspection: 'الزيارة القادمة',
    notScheduled: 'غير محددة',
    openTitle: 'بنود مطلوب معالجتها',
    openEmpty: 'لا توجد بنود مفتوحة.',
    resolvedTitle: 'بنود تم إغلاقها',
    resolvedEmpty: 'لا توجد بنود مغلقة بعد.',
    due: 'المهلة',
    overdue: 'تجاوزت المهلة',
    recommendation: 'الإجراء الموصى به',
    noteLabel: 'صف ما قمت به',
    notePlaceholder: 'مثال: تم استبدال وحدة التبريد بتاريخ ١٨/٨',
    uploadPhoto: 'أرفق إثباتاً',
    submit: 'إرسال الإثبات',
    submitting: 'جارٍ الإرسال…',
    awaitingVerification: 'بانتظار تحقق المفتش',
    verified: 'تم التحقق من المعالجة',
    failed: 'تعذّر إرسال الإثبات. حاول مرة أخرى.',
    loadFailed: 'تعذّر تحميل بيانات المنشأة.',
    // The owner needs to know effort now does not buy a grade now, or the
    // portal reads as a broken promise.
    gradeNote: 'إرسال الإثبات لا يغيّر الدرجة. الدرجة تتحدّث عند التفتيش القادم فقط.',
  },

  sync: {
    title: 'قائمة الإرسال',
    pending: 'بانتظار الإرسال',
    empty: 'لا توجد عناصر بانتظار الإرسال.',
    retry: 'أعد الإرسال',
    retryAll: 'أعد إرسال الكل',
    failedAttempts: 'محاولات فاشلة',
    online: 'متصل',
    offline: 'غير متصل',
    syncing: 'جارٍ الإرسال…',
    sent: 'أُرسل',
    establishment: 'المنشأة',
    savedAt: 'حُفظ في',
  },
} as const;
