/**
 * Every Arabic string in the interface (spec §12.1). Nothing is written inline
 * in a component — one file to review, one file to hand a translator, and no
 * hunting through templates when the municipality changes a term.
 */
export const T = {
  app: {
    name: 'أمان',
    tagline: 'سلامة الغذاء في نابلس',
    authority: 'بلدية نابلس',
    department: 'صحة الأغذية',
    attribution: 'الدرجة صادرة عن بلدية نابلس — أمان أداة بيد البلدية ولا يصدر أي تقييم.',
  },

  home: {
    lede: 'امسح رمز الاستجابة السريعة على باب المنشأة لتطّلع على درجتها الصحية.',
    demoLabel: 'منشأة للعرض',
    inspectorEntry: 'دخول المفتشين',
  },

  common: {
    loading: 'جارٍ التحميل…',
    retry: 'أعد المحاولة',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    cancel: 'إلغاء',
    save: 'حفظ',
    of: 'من',
    day: 'يوم',
    days: 'يوماً',
    none: 'لا يوجد',
  },

  grade: {
    label: 'الدرجة',
    notInspected: 'لم يُفتَّش بعد',
    meaning: {
      A: 'مطابق للمعايير',
      B: 'مخالفات بسيطة',
      C: 'مخالفات مؤثرة تستوجب المتابعة',
      D: 'مخالفات جسيمة تستوجب إجراءً عاجلاً',
    } as Record<string, string>,
  },

  publicPage: {
    recordTitle: 'بيانات السجل',
    lastInspection: 'آخر تفتيش',
    score: 'النتيجة',
    openViolations: 'مخالفات مفتوحة',
    neverInspected: 'لم يسبق تفتيش هذه المنشأة',
    violationsTitle: 'مخالفات قيد المتابعة',
    ownerResponded: 'ردّ صاحب المنشأة وينتظر التحقق',
    historyTitle: 'سجل التفتيش',
    historyEmpty: 'لا يوجد سجل تفتيش سابق.',
    violationsEmpty: 'لا توجد مخالفات مفتوحة.',
    complaintCta: 'قدّم شكوى',
    complaintSoon: 'تقديم الشكاوى يبدأ قريباً',
    suspended: 'هذه المنشأة موقوفة أو مغلقة بقرار من البلدية.',
    notFound: 'هذا الرمز غير مسجّل لدى البلدية.',
    notFoundHint: 'تأكد من مسح الملصق الرسمي الموجود على باب المنشأة.',
  },

  auth: {
    title: 'دخول المفتشين',
    subtitle: 'بلدية نابلس — دائرة صحة الأغذية',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    submit: 'تسجيل الدخول',
    signingIn: 'جارٍ الدخول…',
    failed: 'تعذّر تسجيل الدخول. تحقق من البيانات وحاول مجدداً.',
    signOut: 'تسجيل الخروج',
  },

  queue: {
    title: 'جولة اليوم',
    subtitle: 'مرتّبة حسب الأولوية',
    assigned: 'مسندة اليوم',
    start: 'ابدأ التفتيش',
    resume: 'أكمل التفتيش',
    empty: 'لا توجد منشآت مسندة اليوم.',
    emptyHint: 'اسحب للأسفل لتحديث القائمة.',
    refresh: 'تحديث القائمة',
    lastUpdated: 'آخر تحديث',
    offlineList: 'تعرض القائمة المحفوظة — قد يكون الترتيب قد تغيّر.',
    riskLabel: 'الأولوية',
    riskHigh: 'مرتفعة',
    riskMid: 'متوسطة',
    riskLow: 'منخفضة',
    why: 'سبب الترتيب',
    loadFailed: 'تعذّر تحميل القائمة.',
  },

  checklist: {
    section: 'القسم',
    progress: 'مكتمل',
    runningScore: 'النتيجة الحالية',
    result: { PASS: 'مطابق', FAIL: 'مخالف', NA: 'لا ينطبق' } as Record<string, string>,
    severity: { CRITICAL: 'حرجة', MAJOR: 'كبيرة', MINOR: 'بسيطة' } as Record<string, string>,
    measured: 'القراءة المسجّلة',
    note: 'ملاحظة',
    notePlaceholder: 'موقع القراءة أو تفصيل المخالفة',
    addPhoto: 'أرفق صورة',
    photoRequired: 'المخالفة الحرجة تتطلب صورة قبل المتابعة.',
    photoAttached: 'صورة مرفقة',
    removePhoto: 'حذف الصورة',
    unanswered: 'لم يُجب بعد',
    autosaved: 'محفوظ على الجهاز',
    toReview: 'المراجعة والإرسال',
    incomplete: 'أجب على جميع بنود هذا القسم للمتابعة.',
    loadFailed: 'تعذّر تحميل بيانات المنشأة. اتصل بالشبكة وحاول مجدداً.',
    abandon: 'إنهاء التفتيش وحذف المسودّة',
    abandonConfirm: 'سيتم حذف هذه المسودّة نهائياً. هل تريد المتابعة؟',
  },

  review: {
    title: 'المراجعة والإرسال',
    failedTitle: 'المخالفات المسجّلة',
    noFailures: 'لم تُسجَّل أي مخالفة في هذه الزيارة.',
    outcome: 'نتيجة الزيارة',
    gradeChange: 'تغيّر الدرجة',
    recommendation: 'الإجراء الموصى به',
    recommendationHint: 'يمكنك تعديل النص قبل الإرسال.',
    deadline: 'المهلة',
    signature: 'توقيع المفتش',
    signatureHint: 'وقّع داخل الإطار.',
    clearSignature: 'مسح التوقيع',
    signatureRequired: 'التوقيع مطلوب قبل الإرسال.',
    submit: 'إرسال التفتيش',
    submitting: 'جارٍ الإرسال…',
    confirmTitle: 'الإرسال نهائي',
    confirmBody:
      'لا يمكن تعديل التفتيش بعد إرساله. أي تصحيح يستلزم تفتيشاً جديداً مع بيان السبب.',
    confirmAccept: 'أرسل نهائياً',
    queued: 'لا يوجد اتصال — أُدرج التفتيش في قائمة الإرسال وسيُرسل تلقائياً.',
    submitted: 'تم إرسال التفتيش وتحديث الدرجة.',
    viewPublic: 'اعرض الصفحة العامة',
    backToQueue: 'العودة إلى الجولة',
  },

  sync: {
    title: 'قائمة الإرسال',
    pending: 'بانتظار الإرسال',
    empty: 'لا توجد عناصر بانتظار الإرسال.',
    retry: 'أعد الإرسال',
    retryAll: 'أعد إرسال الكل',
    failedAttempts: 'محاولات فاشلة',
    online: 'متصل',
    offline: 'غير متصل',
    syncing: 'جارٍ الإرسال…',
    sent: 'أُرسل',
    establishment: 'المنشأة',
    savedAt: 'حُفظ في',
  },
} as const;
